version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: faker
    versions:
    - 5.2.0
    - 5.3.1
    - 5.4.0
    - 5.5.0
    - 5.5.1
    - 5.5.2
  - dependency-name: ts-jest
    versions:
    - 26.4.4
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: y18n
    versions:
    - 4.0.1
